### ISSUE TITLE
Pyromancer's Staff, Glacial Rod, Infernal Chalice

### ISSUE THREAD

**Issue by MercuriusXeno** [TrainerGuy22/Reliquary#104]
Changing up the order of upgrades. Dragon claws and the Salamander's Eye will go towards creating a new staff that gives you considerable power over all things fire, but not lava.

Pyromancer's Staff:
Right click = flint and steel
Holding right click = spews close range fire particles, dealing fire damage and setting ablaze anything in front of you.
Shift right click = activates the staff, consuming fire charges or blaze powder to fuel its abilities.
Fire charges are worth substantially more than blaze powder.
Shift + Left click fires a ghast's explosive fireball.
Left click shoots a blaze fireball, blaze fireballs consume less charge.
Holding the staff gives you the powers of the Salamander's Eye.
Facing the "wrong" direction when struck by a ghast fireball will absorb a charge instead.
Absorbs blaze fireballs as well, but they're worth less energy.
Simply having the staff gives you fire damage absorption in exchange for hunger.

Claws of the Firedrinker will be replaced by "Infernal Chalice"
The Infernal Chalice will give you the hunger-damage immunity to lava, but not fire, and also be an "infinite" lava bucket, allowing you to drain source blocks of lava around you [automatically] to fill its charge. Doing so converts them to cobblestone to avoid creating lag. (inspired by Ender Pump + Barrel + Portable).

If inactive, the Infernal Chalice simply functions as a bucket that's always (if charged) full (and always not full) of lava. Right clicking lava source will always consume the source block.

Glacial Staff:
An upgrade to the ice magus rod that improves its storage and damage output, in addition to a frozen debuff (new potion effect: frozen). With it in activated in your inventory, nearby water and lava source blocks will be cooled to Ice and Obsidian, respectively, but they will "reconstitute" once you leave their direct vicinity. Striking a chilled mob with the staff will cause massive damage, but depletes the staff's charge.

**Comment by farron9** [comment]
hola, por que a la hora de craftear el Bastón Glacial no me permite craftear las tijeras de diamante?
