### ISSUE TITLE
ContentHandler performance issues.

### ISSUE THREAD

**Issue by x3n0ph0b3** [TrainerGuy22/Reliquary#208]
lib.enderwizards.sandstone.init.ContentHandler uses stack analysis frequently, e.g. from the entity living event, which is slow.. (direct quote from Player on Forgecraft)

Let's try to circumvent this with another method or use caching, if applicable.

**Comment by TrainerGuy22** [comment]
I originally did this to circumvent having to write ContentHandler.method(MOD_ID, arg) every time. We could move ContentHandler to a instance-based class.

Instead of ContentHandler.getBlock(), you'd write Reliquary.CONTENT.getBlock().
