### ISSUE TITLE
Lantern of Paranoia doesn't place torches in survival mode

### ISSUE THREAD

**Issue by Lebleus** [TrainerGuy22/Reliquary#220]
Hello,

I have an issue with the Lantern of Paranoia. When I use it in creative mode, it works well, but in survival mode, it doesn't work. I'm sure, it's activated and I have one stacks of torches in my inventory.

I have Reliquary 1.2 and Forge 10.13.3.1370

**Comment by SMPantsu** [comment]
I can confirm this, Lantern only works on Creative mode.

Forge 10.13.3.1401-1710ls
Reliquary 1.2

**Comment by spannerman79** [comment]
try http://minecraft.curseforge.com/mc-mods/59713-reliquary/files/2246143

**Comment by Sunery030** [comment]
it uses the torches in the sojourner's staff
